# Generated by Django 2.0.13 on 2019-04-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_core', '0002_auto_20190421_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSQModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True, db_index=True)),
                ('bsq', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BSQ',
                'verbose_name_plural': 'BSQ',
            },
        ),
        migrations.RemoveField(
            model_name='bsq',
            name='brand_model',
        ),
        migrations.RemoveField(
            model_name='bsq',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bsq',
            name='store',
        ),
        migrations.AddField(
            model_name='warehouseinventorymodel',
            name='warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='retail_core.WarehouseModel'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='staticprioritymodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='staticprioritymodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeinventorymodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storeinventorymodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='storeinventorymodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storewarehousemappingmodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='storewarehousemappingmodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='warehouseinventorymodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='warehouseinventorymodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warehouseinventorymodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='warehousemodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='warehousemodel',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='BSQ',
        ),
        migrations.AddField(
            model_name='bsqmodel',
            name='brand_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_core.BrandModel'),
        ),
        migrations.AddField(
            model_name='bsqmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_core.ProductModel'),
        ),
        migrations.AddField(
            model_name='bsqmodel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_core.StoreModel'),
        ),
    ]
