# Generated by Django 2.0.13 on 2019-04-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_core', '0004_replenishmentordermodel_warehouseproductshortqtymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True, db_index=True)),
                ('ranking_model', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=128)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_core.BrandModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
