# Generated by Django 2.0.13 on 2019-04-22 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_core', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True, db_index=True)),
                ('file_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True, db_index=True)),
                ('file_type', models.CharField(max_length=128)),
                ('file', models.FileField(blank=True, upload_to='reviews/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
