# Generated by Django 2.0.13 on 2019-04-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('ranking_model', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=128)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='BSQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bsq', models.IntegerField()),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
            ],
            options={
                'verbose_name': 'BSQ',
                'verbose_name_plural': 'BSQ',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('product_code', models.CharField(db_index=True, max_length=256)),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProductModel')),
            ],
            options={
                'verbose_name': 'Sale Transaction',
                'verbose_name_plural': 'Sales Transactions',
            },
        ),
        migrations.CreateModel(
            name='StaticPriorityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('static_priority_rank', models.IntegerField()),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
            ],
            options={
                'verbose_name': 'Static Priority',
                'verbose_name_plural': 'Static Priorities',
            },
        ),
        migrations.CreateModel(
            name='StoreInventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateTimeField()),
                ('closing_inventory', models.IntegerField()),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProductModel')),
            ],
            options={
                'verbose_name': 'Store Inventory',
                'verbose_name_plural': 'Store Inventory',
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('store_code', models.CharField(db_index=True, max_length=256)),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreWarehouseBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StoreModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateTimeField()),
                ('closing_inventory', models.IntegerField()),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProductModel')),
            ],
            options={
                'verbose_name': 'Warehouse Inventory',
                'verbose_name_plural': 'Warehouse Inventory',
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('warehouse_code', models.CharField(db_index=True, max_length=256)),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BrandModel')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.AddField(
            model_name='storewarehousebinding',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WarehouseModel'),
        ),
        migrations.AddField(
            model_name='storeinventorymodel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StoreModel'),
        ),
        migrations.AddField(
            model_name='staticprioritymodel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StoreModel'),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StoreModel'),
        ),
        migrations.AddField(
            model_name='bsq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProductModel'),
        ),
        migrations.AddField(
            model_name='bsq',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StoreModel'),
        ),
    ]
